//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC3_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLAIM
    {
        public CLAIM()
        {
            this.ESTIMATE = new HashSet<ESTIMATE>();
            this.PROBLEM = new HashSet<PROBLEM>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> CLAIM_DATE { get; set; }
        public string STATUS { get; set; }
        public Nullable<decimal> CLAIM_AMT { get; set; }
        public Nullable<bool> CLAIMDISPURSED { get; set; }
        public string DETAIL_NOTE { get; set; }
        public Nullable<int> APPROVED_BY { get; set; }
        public Nullable<int> APPROVED_TO { get; set; }
        public Nullable<System.DateTime> APPROVED_DATE { get; set; }
        public Nullable<decimal> DEDUCTIBLE { get; set; }
        public Nullable<decimal> NET_AMT { get; set; }
        public Nullable<decimal> AGREED_AMT { get; set; }
        public Nullable<int> CUSTOMER_ID { get; set; }
        public Nullable<int> PROCESS_EMPLOYEE_ID { get; set; }
        public Nullable<int> CHEQUE_ID { get; set; }
        public Nullable<int> AUDIT_INFO_ID { get; set; }
    
        public virtual AUDIT_INFO AUDIT_INFO { get; set; }
        public virtual CHEQUE CHEQUE { get; set; }
        public virtual CLAIM_STATUS_CODE CLAIM_STATUS_CODE { get; set; }
        public virtual CLIENT CLIENT { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual EMPLOYEE EMPLOYEE1 { get; set; }
        public virtual ICollection<ESTIMATE> ESTIMATE { get; set; }
        public virtual ICollection<PROBLEM> PROBLEM { get; set; }
    }
}
