//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC3_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT
    {
        public CLIENT()
        {
            this.CLAIM = new HashSet<CLAIM>();
            this.VEHICLE_OWNER = new HashSet<VEHICLE_OWNER>();
        }
    
        public int ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public Nullable<System.DateTime> SIGN_UP_DATE { get; set; }
        public Nullable<int> CONTACT_INFO_ID { get; set; }
        public Nullable<int> AUDIT_INFO_ID { get; set; }
    
        public virtual AUDIT_INFO AUDIT_INFO { get; set; }
        public virtual ICollection<CLAIM> CLAIM { get; set; }
        public virtual CONTACT_INFO CONTACT_INFO { get; set; }
        public virtual ICollection<VEHICLE_OWNER> VEHICLE_OWNER { get; set; }
    }
}
