//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC3_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COLOR
    {
        public COLOR()
        {
            this.VEHICLE = new HashSet<VEHICLE>();
        }
    
        public int ID { get; set; }
        public string COLOR1 { get; set; }
    
        public virtual ICollection<VEHICLE> VEHICLE { get; set; }
    }
}
