//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC3_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACT_INFO
    {
        public CONTACT_INFO()
        {
            this.CLIENT = new HashSet<CLIENT>();
            this.DEALERSHIP = new HashSet<DEALERSHIP>();
            this.EMPLOYEE = new HashSet<EMPLOYEE>();
            this.REPAIRSHOP = new HashSet<REPAIRSHOP>();
        }
    
        public int ID { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string CITY { get; set; }
        public string PROVINCE { get; set; }
        public string POSTAL_CODE { get; set; }
        public string CELLPHONE { get; set; }
        public string EMAIL { get; set; }
        public string WORK_PHONE { get; set; }
        public string FAX { get; set; }
        public string REP_NAME { get; set; }
        public Nullable<int> AUDIT_INFO_ID { get; set; }
    
        public virtual AUDIT_INFO AUDIT_INFO { get; set; }
        public virtual ICollection<CLIENT> CLIENT { get; set; }
        public virtual PROVINCE PROVINCE1 { get; set; }
        public virtual ICollection<DEALERSHIP> DEALERSHIP { get; set; }
        public virtual ICollection<EMPLOYEE> EMPLOYEE { get; set; }
        public virtual ICollection<REPAIRSHOP> REPAIRSHOP { get; set; }
    }
}
