//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC3_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEALERSHIP_AGREEMENT
    {
        public DEALERSHIP_AGREEMENT()
        {
            this.AGREEMENT_PRODUCT = new HashSet<AGREEMENT_PRODUCT>();
        }
    
        public int AGREEMENT_NUM { get; set; }
        public Nullable<int> DEALERSHIP_ID { get; set; }
        public Nullable<System.DateTime> SIGNED_DATE { get; set; }
        public Nullable<System.DateTime> EXPIRED_DATE { get; set; }
        public Nullable<int> AUDIT_INFO_ID { get; set; }
    
        public virtual ICollection<AGREEMENT_PRODUCT> AGREEMENT_PRODUCT { get; set; }
        public virtual AUDIT_INFO AUDIT_INFO { get; set; }
        public virtual DEALERSHIP DEALERSHIP { get; set; }
    }
}
