//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC3_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEALERSHIP_PRODUCT
    {
        public int ID { get; set; }
        public Nullable<int> DEALERSHIP_ID { get; set; }
        public Nullable<int> PRODUCT_ID { get; set; }
        public Nullable<int> QTY_ON_HAND { get; set; }
        public Nullable<int> AUDIT_INFO_ID { get; set; }
    
        public virtual AUDIT_INFO AUDIT_INFO { get; set; }
        public virtual DEALERSHIP DEALERSHIP { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
