//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC3_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEALERSHIP
    {
        public DEALERSHIP()
        {
            this.DEALERSHIP_AGREEMENT = new HashSet<DEALERSHIP_AGREEMENT>();
            this.DEALERSHIP_PRODUCT = new HashSet<DEALERSHIP_PRODUCT>();
            this.INSPECTION = new HashSet<INSPECTION>();
            this.ORDER = new HashSet<ORDER>();
            this.WARRANTY = new HashSet<WARRANTY>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<System.DateTime> DATE_JOINED { get; set; }
        public Nullable<System.DateTime> DATE_INACTIVATED { get; set; }
        public Nullable<int> CONTACT_INFO_ID { get; set; }
        public Nullable<int> AUDIT_INFO_ID { get; set; }
    
        public virtual AUDIT_INFO AUDIT_INFO { get; set; }
        public virtual CONTACT_INFO CONTACT_INFO { get; set; }
        public virtual ICollection<DEALERSHIP_AGREEMENT> DEALERSHIP_AGREEMENT { get; set; }
        public virtual ICollection<DEALERSHIP_PRODUCT> DEALERSHIP_PRODUCT { get; set; }
        public virtual ICollection<INSPECTION> INSPECTION { get; set; }
        public virtual ICollection<ORDER> ORDER { get; set; }
        public virtual ICollection<WARRANTY> WARRANTY { get; set; }
    }
}
