//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC3_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTMENT
    {
        public DEPARTMENT()
        {
            this.EMPLOYEE = new HashSet<EMPLOYEE>();
        }
    
        public int ID { get; set; }
        public string DEPTNAME { get; set; }
        public string DEPTLOCATION { get; set; }
    
        public virtual ICollection<EMPLOYEE> EMPLOYEE { get; set; }
    }
}
