//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC3_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSPECTION_TYPE_CODE
    {
        public INSPECTION_TYPE_CODE()
        {
            this.INSPECTION = new HashSet<INSPECTION>();
        }
    
        public string INSPECTION_TYPE_CODE1 { get; set; }
        public string TYPE_DESC { get; set; }
    
        public virtual ICollection<INSPECTION> INSPECTION { get; set; }
    }
}
