//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC3_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSPECTION
    {
        public INSPECTION()
        {
            this.ESTIMATE = new HashSet<ESTIMATE>();
            this.INSPECTION_FILE = new HashSet<INSPECTION_FILE>();
        }
    
        public int ID { get; set; }
        public Nullable<int> DEALERSHIP_ID { get; set; }
        public Nullable<int> REPAIRSHOP_ID { get; set; }
        public Nullable<System.DateTime> DUE_DATE { get; set; }
        public Nullable<System.DateTime> INSPECT_DATE { get; set; }
        public string STATUS_CODE { get; set; }
        public string RESULT_DESC { get; set; }
        public string INSPECTION_TYPE { get; set; }
        public Nullable<int> VEHICLE_ID { get; set; }
        public Nullable<int> WARRANTY_NUMBER { get; set; }
        public Nullable<int> AUDIT_INFO_ID { get; set; }
    
        public virtual AUDIT_INFO AUDIT_INFO { get; set; }
        public virtual DEALERSHIP DEALERSHIP { get; set; }
        public virtual ICollection<ESTIMATE> ESTIMATE { get; set; }
        public virtual ICollection<INSPECTION_FILE> INSPECTION_FILE { get; set; }
        public virtual INSPECTION_STATUS_CODE INSPECTION_STATUS_CODE { get; set; }
        public virtual INSPECTION_TYPE_CODE INSPECTION_TYPE_CODE { get; set; }
        public virtual REPAIRSHOP REPAIRSHOP { get; set; }
        public virtual VEHICLE VEHICLE { get; set; }
        public virtual WARRANTY WARRANTY { get; set; }
    }
}
