//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC3_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVOICE
    {
        public INVOICE()
        {
            this.INVOICE_ORDER = new HashSet<INVOICE_ORDER>();
            this.PAYMENT = new HashSet<PAYMENT>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<int> DEALERSHIP_ID { get; set; }
        public Nullable<decimal> TOTAL_AMT { get; set; }
        public Nullable<int> AUDIT_INFO_ID { get; set; }
    
        public virtual AUDIT_INFO AUDIT_INFO { get; set; }
        public virtual ICollection<INVOICE_ORDER> INVOICE_ORDER { get; set; }
        public virtual ICollection<PAYMENT> PAYMENT { get; set; }
    }
}
