//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC3_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVOICE_ORDER
    {
        public int ID { get; set; }
        public Nullable<int> INVOICE_ID { get; set; }
        public Nullable<int> ORDER_ID { get; set; }
        public Nullable<int> AUDIT_INFO_ID { get; set; }
    
        public virtual AUDIT_INFO AUDIT_INFO { get; set; }
        public virtual INVOICE INVOICE { get; set; }
        public virtual ORDER ORDER { get; set; }
    }
}
