//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC3_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        public ORDER()
        {
            this.INVOICE_ORDER = new HashSet<INVOICE_ORDER>();
            this.ORDER_ITEMS = new HashSet<ORDER_ITEMS>();
        }
    
        public int ID { get; set; }
        public Nullable<int> DEALERSHIP_ID { get; set; }
        public Nullable<System.DateTime> SHIPMENT_DATE { get; set; }
        public Nullable<System.DateTime> ORDER_DATE { get; set; }
        public Nullable<decimal> TAX { get; set; }
        public Nullable<decimal> AMT_TOTAL { get; set; }
        public string ORDER_STATUS { get; set; }
        public Nullable<int> AUDIT_INFO_ID { get; set; }
    
        public virtual AUDIT_INFO AUDIT_INFO { get; set; }
        public virtual DEALERSHIP DEALERSHIP { get; set; }
        public virtual ICollection<INVOICE_ORDER> INVOICE_ORDER { get; set; }
        public virtual ICollection<ORDER_ITEMS> ORDER_ITEMS { get; set; }
        public virtual ORDER_STATUS_CODE ORDER_STATUS_CODE { get; set; }
    }
}
