//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC3_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROBLEM_TYPE
    {
        public PROBLEM_TYPE()
        {
            this.PROBLEM = new HashSet<PROBLEM>();
            this.PROBLEM_DESCRIPTION = new HashSet<PROBLEM_DESCRIPTION>();
        }
    
        public string TYPE_CODE { get; set; }
        public string TYPE_DESC { get; set; }
    
        public virtual ICollection<PROBLEM> PROBLEM { get; set; }
        public virtual ICollection<PROBLEM_DESCRIPTION> PROBLEM_DESCRIPTION { get; set; }
    }
}
