//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC3_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROBLEM_DESCRIPTION
    {
        public int ID { get; set; }
        public string DESCRIPTION { get; set; }
        public string PROBLEM_TYPE_CODE { get; set; }
    
        public virtual PROBLEM_TYPE PROBLEM_TYPE { get; set; }
    }
}
