//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC3_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public PRODUCT()
        {
            this.AGREEMENT_PRODUCT = new HashSet<AGREEMENT_PRODUCT>();
            this.DEALERSHIP_PRODUCT = new HashSet<DEALERSHIP_PRODUCT>();
            this.ORDER_ITEMS = new HashSet<ORDER_ITEMS>();
            this.PROBLEM = new HashSet<PROBLEM>();
            this.WARRANTY = new HashSet<WARRANTY>();
        }
    
        public int PRODUCT_ID { get; set; }
        public string PRODUCT_NAME { get; set; }
        public string PRODUCT_DESC { get; set; }
        public Nullable<decimal> BASE_PRICE { get; set; }
        public Nullable<decimal> MAX_DISCOUNT { get; set; }
        public Nullable<decimal> PRODUCTION_COST { get; set; }
        public string PRODUCT_CATEGORY { get; set; }
        public Nullable<int> QTY_ON_HAND { get; set; }
        public Nullable<int> AUDIT_INFO_ID { get; set; }
    
        public virtual ICollection<AGREEMENT_PRODUCT> AGREEMENT_PRODUCT { get; set; }
        public virtual AUDIT_INFO AUDIT_INFO { get; set; }
        public virtual ICollection<DEALERSHIP_PRODUCT> DEALERSHIP_PRODUCT { get; set; }
        public virtual ICollection<ORDER_ITEMS> ORDER_ITEMS { get; set; }
        public virtual ICollection<PROBLEM> PROBLEM { get; set; }
        public virtual PRODUCT_CATEGORY PRODUCT_CATEGORY1 { get; set; }
        public virtual ICollection<WARRANTY> WARRANTY { get; set; }
    }
}
