//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC3_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_CATEGORY
    {
        public PRODUCT_CATEGORY()
        {
            this.PRODUCT = new HashSet<PRODUCT>();
        }
    
        public string CATEGORY_CODE { get; set; }
        public string CATEGORY_NAME { get; set; }
        public Nullable<int> AUDIT_INFO { get; set; }
    
        public virtual ICollection<PRODUCT> PRODUCT { get; set; }
    }
}
