//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC3_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVINCE
    {
        public PROVINCE()
        {
            this.CITY = new HashSet<CITY>();
            this.CONTACT_INFO = new HashSet<CONTACT_INFO>();
        }
    
        public string PROVINCE_CODE { get; set; }
        public string PROVINCE_NAME { get; set; }
    
        public virtual ICollection<CITY> CITY { get; set; }
        public virtual ICollection<CONTACT_INFO> CONTACT_INFO { get; set; }
    }
}
