//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC3_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UC3Entities : DbContext
    {
        public UC3Entities()
            : base("name=UC3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AGREEMENT_PRODUCT> AGREEMENT_PRODUCT { get; set; }
        public virtual DbSet<AUDIT_INFO> AUDIT_INFO { get; set; }
        public virtual DbSet<CHEQUE> CHEQUE { get; set; }
        public virtual DbSet<CHEQUE_STATUS> CHEQUE_STATUS { get; set; }
        public virtual DbSet<CITY> CITY { get; set; }
        public virtual DbSet<CLAIM> CLAIM { get; set; }
        public virtual DbSet<CLAIM_STATUS_CODE> CLAIM_STATUS_CODE { get; set; }
        public virtual DbSet<CLIENT> CLIENT { get; set; }
        public virtual DbSet<COLOR> COLOR { get; set; }
        public virtual DbSet<CONTACT_INFO> CONTACT_INFO { get; set; }
        public virtual DbSet<DEALERSHIP> DEALERSHIP { get; set; }
        public virtual DbSet<DEALERSHIP_AGREEMENT> DEALERSHIP_AGREEMENT { get; set; }
        public virtual DbSet<DEALERSHIP_PRODUCT> DEALERSHIP_PRODUCT { get; set; }
        public virtual DbSet<DEPARTMENT> DEPARTMENT { get; set; }
        public virtual DbSet<EMPLOYEE> EMPLOYEE { get; set; }
        public virtual DbSet<ESTIMATE> ESTIMATE { get; set; }
        public virtual DbSet<FILE> FILE { get; set; }
        public virtual DbSet<INSPECTION> INSPECTION { get; set; }
        public virtual DbSet<INSPECTION_FILE> INSPECTION_FILE { get; set; }
        public virtual DbSet<INSPECTION_STATUS_CODE> INSPECTION_STATUS_CODE { get; set; }
        public virtual DbSet<INSPECTION_TYPE_CODE> INSPECTION_TYPE_CODE { get; set; }
        public virtual DbSet<INVOICE> INVOICE { get; set; }
        public virtual DbSet<INVOICE_ORDER> INVOICE_ORDER { get; set; }
        public virtual DbSet<MEDIA_TYPE> MEDIA_TYPE { get; set; }
        public virtual DbSet<ORDER> ORDER { get; set; }
        public virtual DbSet<ORDER_ITEMS> ORDER_ITEMS { get; set; }
        public virtual DbSet<ORDER_STATUS_CODE> ORDER_STATUS_CODE { get; set; }
        public virtual DbSet<PAYMENT> PAYMENT { get; set; }
        public virtual DbSet<PROBLEM> PROBLEM { get; set; }
        public virtual DbSet<PROBLEM_DESCRIPTION> PROBLEM_DESCRIPTION { get; set; }
        public virtual DbSet<PROBLEM_TYPE> PROBLEM_TYPE { get; set; }
        public virtual DbSet<PRODUCT> PRODUCT { get; set; }
        public virtual DbSet<PRODUCT_CATEGORY> PRODUCT_CATEGORY { get; set; }
        public virtual DbSet<PROVINCE> PROVINCE { get; set; }
        public virtual DbSet<REPAIRSHOP> REPAIRSHOP { get; set; }
        public virtual DbSet<SIDE_CODE> SIDE_CODE { get; set; }
        public virtual DbSet<VEHICLE> VEHICLE { get; set; }
        public virtual DbSet<VEHICLE_MAKE> VEHICLE_MAKE { get; set; }
        public virtual DbSet<VEHICLE_OWNER> VEHICLE_OWNER { get; set; }
        public virtual DbSet<VEHICLE_PART> VEHICLE_PART { get; set; }
        public virtual DbSet<WARRANTY> WARRANTY { get; set; }
        public virtual DbSet<WARRANTY_STATUS> WARRANTY_STATUS { get; set; }
        public virtual DbSet<WARRANTY_TYPE> WARRANTY_TYPE { get; set; }
    }
}
