//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC3_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class stle2Entities : DbContext
    {
        public stle2Entities()
            : base("name=stle2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AGREEMENT_PRODUCT> AGREEMENT_PRODUCT { get; set; }
        public DbSet<AUDIT_INFO> AUDIT_INFO { get; set; }
        public DbSet<CHEQUE> CHEQUE { get; set; }
        public DbSet<CHEQUE_STATUS> CHEQUE_STATUS { get; set; }
        public DbSet<CITY> CITY { get; set; }
        public DbSet<CLAIM> CLAIM { get; set; }
        public DbSet<CLAIM_STATUS_CODE> CLAIM_STATUS_CODE { get; set; }
        public DbSet<CLIENT> CLIENT { get; set; }
        public DbSet<COLOR> COLOR { get; set; }
        public DbSet<CONTACT_INFO> CONTACT_INFO { get; set; }
        public DbSet<DEALERSHIP> DEALERSHIP { get; set; }
        public DbSet<DEALERSHIP_AGREEMENT> DEALERSHIP_AGREEMENT { get; set; }
        public DbSet<DEALERSHIP_PRODUCT> DEALERSHIP_PRODUCT { get; set; }
        public DbSet<DEPARTMENT> DEPARTMENT { get; set; }
        public DbSet<EMPLOYEE> EMPLOYEE { get; set; }
        public DbSet<ESTIMATE> ESTIMATE { get; set; }
        public DbSet<FILE> FILE { get; set; }
        public DbSet<INSPECTION> INSPECTION { get; set; }
        public DbSet<INSPECTION_FILE> INSPECTION_FILE { get; set; }
        public DbSet<INSPECTION_STATUS_CODE> INSPECTION_STATUS_CODE { get; set; }
        public DbSet<INSPECTION_TYPE_CODE> INSPECTION_TYPE_CODE { get; set; }
        public DbSet<INVOICE> INVOICE { get; set; }
        public DbSet<INVOICE_ORDER> INVOICE_ORDER { get; set; }
        public DbSet<MEDIA_TYPE> MEDIA_TYPE { get; set; }
        public DbSet<ORDER> ORDER { get; set; }
        public DbSet<ORDER_ITEMS> ORDER_ITEMS { get; set; }
        public DbSet<ORDER_STATUS_CODE> ORDER_STATUS_CODE { get; set; }
        public DbSet<PAYMENT> PAYMENT { get; set; }
        public DbSet<PROBLEM> PROBLEM { get; set; }
        public DbSet<PROBLEM_DESCRIPTION> PROBLEM_DESCRIPTION { get; set; }
        public DbSet<PROBLEM_TYPE> PROBLEM_TYPE { get; set; }
        public DbSet<PRODUCT> PRODUCT { get; set; }
        public DbSet<PRODUCT_CATEGORY> PRODUCT_CATEGORY { get; set; }
        public DbSet<PROVINCE> PROVINCE { get; set; }
        public DbSet<REPAIRSHOP> REPAIRSHOP { get; set; }
        public DbSet<SIDE_CODE> SIDE_CODE { get; set; }
        public DbSet<VEHICLE> VEHICLE { get; set; }
        public DbSet<VEHICLE_MAKE> VEHICLE_MAKE { get; set; }
        public DbSet<VEHICLE_OWNER> VEHICLE_OWNER { get; set; }
        public DbSet<VEHICLE_PART> VEHICLE_PART { get; set; }
        public DbSet<WARRANTY> WARRANTY { get; set; }
        public DbSet<WARRANTY_STATUS> WARRANTY_STATUS { get; set; }
        public DbSet<WARRANTY_TYPE> WARRANTY_TYPE { get; set; }
    }
}
