//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC3_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICLE_PART
    {
        public VEHICLE_PART()
        {
            this.PROBLEM = new HashSet<PROBLEM>();
        }
    
        public int PARTID { get; set; }
        public string PART_DESC { get; set; }
        public string SIDE_CODE { get; set; }
    
        public virtual ICollection<PROBLEM> PROBLEM { get; set; }
        public virtual SIDE_CODE SIDE_CODE1 { get; set; }
    }
}
