//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC3_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICLE
    {
        public VEHICLE()
        {
            this.INSPECTION = new HashSet<INSPECTION>();
            this.VEHICLE_OWNER = new HashSet<VEHICLE_OWNER>();
            this.WARRANTY = new HashSet<WARRANTY>();
        }
    
        public int ID { get; set; }
        public string MODEL { get; set; }
        public string YEAR { get; set; }
        public Nullable<int> COLOR { get; set; }
        public string ODOM { get; set; }
        public string VIN { get; set; }
        public Nullable<int> MAKE { get; set; }
        public Nullable<int> AUDIT_INFO_ID { get; set; }
    
        public virtual AUDIT_INFO AUDIT_INFO { get; set; }
        public virtual COLOR COLOR1 { get; set; }
        public virtual ICollection<INSPECTION> INSPECTION { get; set; }
        public virtual ICollection<VEHICLE_OWNER> VEHICLE_OWNER { get; set; }
        public virtual VEHICLE_MAKE VEHICLE_MAKE { get; set; }
        public virtual ICollection<WARRANTY> WARRANTY { get; set; }
    }
}
