//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC3_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WARRANTY
    {
        public WARRANTY()
        {
            this.INSPECTION = new HashSet<INSPECTION>();
            this.PROBLEM = new HashSet<PROBLEM>();
        }
    
        public int WARRANTY_NUM { get; set; }
        public Nullable<System.DateTime> EFFECTIVE_DATE { get; set; }
        public Nullable<System.DateTime> PROCESSED_DATE { get; set; }
        public Nullable<System.DateTime> EXPIRED_DATE { get; set; }
        public Nullable<System.DateTime> VOID_DATE { get; set; }
        public Nullable<decimal> DEDUCTIBLE { get; set; }
        public string COMMENT { get; set; }
        public string STATUS { get; set; }
        public Nullable<int> DEALER_ID { get; set; }
        public Nullable<int> VEHICLE_ID { get; set; }
        public string WARRANTY_TYPE { get; set; }
        public Nullable<int> PRODUCT_ID { get; set; }
        public Nullable<int> AUDIT_INFO_ID { get; set; }
    
        public virtual AUDIT_INFO AUDIT_INFO { get; set; }
        public virtual DEALERSHIP DEALERSHIP { get; set; }
        public virtual ICollection<INSPECTION> INSPECTION { get; set; }
        public virtual ICollection<PROBLEM> PROBLEM { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual VEHICLE VEHICLE { get; set; }
        public virtual WARRANTY_STATUS WARRANTY_STATUS { get; set; }
        public virtual WARRANTY_TYPE WARRANTY_TYPE1 { get; set; }
    }
}
