//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC3_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WARRANTY_STATUS
    {
        public WARRANTY_STATUS()
        {
            this.WARRANTY = new HashSet<WARRANTY>();
        }
    
        public string STATUS_CODE { get; set; }
        public string STATUS_DESC { get; set; }
    
        public virtual ICollection<WARRANTY> WARRANTY { get; set; }
    }
}
