//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC3_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WARRANTY_TYPE
    {
        public WARRANTY_TYPE()
        {
            this.WARRANTY = new HashSet<WARRANTY>();
        }
    
        public string WARRANTY_TYPE_CODE { get; set; }
        public string NAME { get; set; }
        public string TYPE_DESC { get; set; }
        public Nullable<int> INSPECTION_PERIOD_DAYS { get; set; }
        public Nullable<int> MAX_WARRANTEE_DAYS { get; set; }
        public Nullable<int> INSPECTION_PERIOD_YEARS { get; set; }
        public Nullable<int> MAX_WARRANTEE_YEARS { get; set; }
        public Nullable<int> AUDIT_INFO_ID { get; set; }
    
        public virtual AUDIT_INFO AUDIT_INFO { get; set; }
        public virtual ICollection<WARRANTY> WARRANTY { get; set; }
    }
}
